handler: handlers/akng/locations.getLocations
name: ${self:custom.constants.defaults.prefix}${self:service}-get
events:
  - http:
      path: /
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization