handler: handlers/products.saveProduct
name: ${self:custom.constants.defaults.prefix}${self:service}-save
events:
  - http:
      path: /
      method: post
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization