handler: handlers/categories.getCategoryById
name: ${self:custom.constants.defaults.prefix}${self:service}-getById
events:
  - http:
      path: /{id}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization